typeof 40
console.log(typeof 40);
typeof "Diego"
console.log(typeof "Diego");
typeof true
console.log(typeof true);
typeof null
console.log(typeof null);
typeof undefined
console.log(typeof undefined);
typeof []
console.log(typeof []);
typeof {}
console.log(typeof {});